spring:
  application:
    name: BananaInvoicesAuthServer
  security:
    oauth2:
      client:
        registration:
          client-secret: secret
server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO